CREATE DATABASE IF NOT EXISTS discos;
USE discos;

CREATE TABLE IF NOT EXISTS lanzamientos (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100) NOT NULL,
descripcion VARCHAR(500) NOT NULL,
precio DECIMAL(5,2) UNSIGNED NOT NULL,
imagen VARCHAR(1000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS pedidos ( 
pedido_id INT NOT NULL AUTO_INCREMENT, 
producto_id INT NOT NULL, 
nombre_producto VARCHAR(100) NOT NULL, 
precio_producto DECIMAL(5,2) NOT NULL, 
fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
n_pedido INT(11) NOT NULL, 
PRIMARY KEY (pedido_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;